blog/urls.py
from django.urls import path
from . import views
from django.contrib.sitemaps.views import sitemap
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
 # post views
 path('', views.post_list, name='post_list'),
 path('tag/<slug:tag_slug>/',
      views.post_list, 
      name='post_list_by_tag'),
 path('<int:year>/<int:month>/<int:day>/<slug:post>/',
      views.post_detail,
      name='post_detail'),
path('<int:post_id>/share/',
      views.post_share, 
      name='post_share'),
path('<int:post_id>/comment/',
      views.post_comment, name='post_comment'),
path('feed/', LatestPostsFeed(), name='post_feed'),
path('about/', views.about_us, name='about_us'),
path('contactus/', views.contact_us, name='contact_us'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap



sitemaps = {
 'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('ckeditor/',include('ckeditor_uploader.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap')
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
from ckeditor_uploader.fields import RichTextUploadingField 

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)
    
class Post(models.Model):
    
    class Status(models.TextChoices):
          DRAFT = 'DF', 'Draft'
          PUBLISHED = 'PB', 'Published'
                     
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    author = models.ForeignKey(User,
                on_delete=models.CASCADE,
                related_name='blog_posts')
    body=RichTextUploadingField() 
    body_summary=models.TextField(max_length=500)
    image = models.ImageField(upload_to='media/Post_images/%Y/%m/%d/')
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2,
                                choices=Status.choices,
                                default=Status.DRAFT)
    objects = models.Manager() # The default manager.
    published = PublishedManager() # Our custom manager.
    tags = TaggableManager()
    
    class Meta:
          ordering = ['-publish']
          verbose_name_plural = "Post" 
          indexes = [
             models.Index(fields=['-publish']),
            ]
 
 
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('blog:post_detail',
                        args=[
                             self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug])
                  
class Email(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    to = models.EmailField()
    comments = models.CharField(max_length=50)

    def __str__(self):
        return self.name  
    
    class Meta:
        verbose_name_plural = "Email"  
    
    
    
class Comment(models.Model):
    post = models.ForeignKey(Post,
                                on_delete=models.CASCADE,
                                related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    
    class Meta:
        ordering = ['created']
        verbose_name_plural = "Comment" 
        indexes = [
                 models.Index(fields=['created']),
        ]
        
    def __str__(self):
        return f'Comment by {self.name} on {self.post}'  

class Contact(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    subject = models.CharField(max_length=50)
    message = models.TextField(max_length=100)

    def __str__(self):
        return self.name
    class Meta:
        verbose_name_plural = "Contact"  

class About(models.Model):
    mission = models.TextField(max_length=1000)
    aboutme = models.TextField(max_length=1000)
    mission_pic = models.ImageField(upload_to='media/Mission_images/%Y/%m/%d/')
    aboutme_pic = models.ImageField(upload_to='media/Aboutme_images/%Y/%m/%d/')
    
    class Meta:
        verbose_name_plural = "About"
  
    
    
class OurTeam(models.Model):
    name = models.CharField(max_length=50)
    position = models.CharField(max_length=50)
    profile = models.ImageField(upload_to='media/Ourteam_images/%Y/%m/%d/')
    about= models.TextField(max_length=1000)

    def __str__(self):
        return self.name 
    
    class Meta:
        verbose_name_plural = "OurTeam"

    
    
class Contact_details(models.Model):
    Address = models.CharField(max_length=100)
    phone_Number = models.CharField(max_length=50)
    email = models.EmailField()
    
    def __str__(self):
        return self.email
    
    class Meta:
        verbose_name_plural = "Contact_details"

                       
                        
                         

blog/forms.py
from django import forms
from .models import Email,Comment,Contact

class EmailPostForm(forms.ModelForm):
    class Meta:
        model = Email
        fields = '__all__'
        widgets = {
            'name':forms.TextInput(attrs={'class':'form-control'}),   
            'email':forms.EmailInput(attrs={'class':'form-control'}), 
            'to':forms.TextInput(attrs={'class':'form-control'}), 
            'comments':forms.Textarea(attrs={'class':'form-control'}), 
        }
        
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']
        widgets = {
            'name':forms.TextInput(attrs={'class':'form-control'}),   
            'email':forms.EmailInput(attrs={'class':'form-control'}), 
            'body':forms.Textarea(attrs={'class':'form-control'}), 
        }

class SearchForm(forms.Form):
      query = forms.CharField()
          
class Contactform(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'
        widgets = {
            'name':forms.TextInput(attrs={'class':'form-control'}),   
            'email':forms.EmailInput(attrs={'class':'form-control'}), 
            'subject':forms.TextInput(attrs={'class':'form-control'}), 
            'Message':forms.Textarea(attrs={'class':'form-control'}), 
        }

blog/views.py
from django.shortcuts import render
from .models import Post,Comment,About,OurTeam,Contact_details
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.core.mail import send_mail
from .forms import EmailPostForm, CommentForm,SearchForm,Contactform
from django.views.decorators.http import require_POST
from taggit.models import Tag
from django.db.models import Count
from django.contrib.postgres.search import SearchVector

def post_list(request, tag_slug=None):
    post_list = Post.published.all()
    tag = None
    if tag_slug:
       tag = get_object_or_404(Tag, slug=tag_slug)
       post_list = post_list.filter(tags__in=[tag])

    # Pagination with 3 posts per page
    paginator = Paginator(post_list, 3)
    page_number = request.GET.get('page', 1)
    try:
            posts = paginator.page(page_number)
            
    except PageNotAnInteger:
           # If page_number is not an integer deliver the first page
           posts = paginator.page(1)
    except EmptyPage:
            # If page_number is out of range deliver last page of results
            posts = paginator.page(paginator.num_pages)
    return render(request,
                 'blog/post/list.html',
                 {'posts': posts,
                  'tag': tag})
    
    
def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post,
                             status=Post.Status.PUBLISHED,
                             slug=post,
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)
    # List of active comments for this post
    comments = post.comments.filter(active=True)
    # Form for users to comment
    form = CommentForm()
    # List of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:4]
    return render(request,
                'blog/post/detail.html',
                {'post': post,
                'comments': comments,
                'form': form,
                'similar_posts': similar_posts})

def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    sent = False
    
    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(
                                                  post.get_absolute_url())
            subject = f"{cd['name']} recommends you read " f"{post.title}"
            message = f"Read {post.title} at {post_url}\n\n" f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'junioralexio607@gmail.com',
            [cd['to']])
            sent = True
            # ... send email
            # Save the email to the database
            form.save()
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post,
                            'form': form,
                            'sent': sent})
    
@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None
    # A comment was posted
    form = CommentForm(data=request.POST)
    if form.is_valid():
        # Create a Comment object without saving it to the database
        comment = form.save(commit=False)
        # Assign the post to the comment
        comment.post = post
        # Save the comment to the database
        comment.save()
    return render(request, 'blog/post/comment.html',
                            {'post': post,
                            'form': form,
                            'comment': comment})  
    
def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = Post.published.annotate(search=SearchVector('title', 'body'),).filter(search=query)
            return render(request,
                         'blog/post/search.html',
                         {'form': form,
                         'query': query,
                         'results': results})
 
def contact_us(request):
    Contact_info = Contact_details.objects.all()
    if request.method == 'POST':
        # Form was submitted
        form = Contactform(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            subject = f"{cd['name']}  with email {cd['email']}  Sent you a message  from  topDevBlog:{cd['subject']} "
            message = f"Message: {cd['message']}"
            send_mail(subject, message, 'junioralexio607@gmail.com',
            ['junioralexio607@gmail.com'])
            sent = True
            # ... send email
            return render(request, 'blog/post/contact.html', 
                  {'Contact_info': Contact_info,
                   'form': form,
                   'sent': sent})
        
    else:
        form = Contactform()
    return render(request, 'blog/post/contact.html', 
                  {'Contact_info': Contact_info,
                   'form': form})

def about_us(request):
    about = About.objects.all()
    ourteam = OurTeam.objects.all()
    
    return render(request,
                'blog/post/about.html',
                {'about': about,
                'ourteam': ourteam,
                })
    

blog/templates/blog/base/base.html
{% load static %}

<!DOCTYPE html>
<html>

 <head>
    
 <meta charset="utf-8" />
 <title>{% block title %}{% endblock %}</title>
 <meta content="" name="description">
 <meta content="" name="keywords">
 <meta charset="utf-8">
 <meta content="width=device-width, initial-scale=1.0" name="viewport">

 <!-- Favicons -->
 <link href="{%static "assets/img/logo.png" %}" rel="icon">
 <link href="{%static "assets/img/logo.png" %}" rel="apple-touch-icon">

 <!-- Google Fonts -->
 <link rel="preconnect" href="https://fonts.googleapis.com">
 <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
 <link href="https://fonts.googleapis.com/css2?family=EB+Garamond:wght@400;500&family=Inter:wght@400;500&family=Playfair+Display:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">


 
 <!-- Css and Js files -->
 {% include 'blog/base/scripts.html' %}
  <!-- Css and Js files -->


 <!-- header files -->
 {% include 'blog/base/header.html' %}
 <!-- header files -->
 
 </head>


 <body>
 
 {% block content %}
 
 {% endblock %}


<!-- footer -->
{% include 'blog/base/footer.html' %}
<!-- footer -->


{% comment %} <!-- js files -->
{% include 'shop/js.html' %}
<!-- js files --> {% endcomment %}


 </body>
</html

blog/templates/blog/base/footer.html
  <!-- ======= Footer ======= -->
  <footer id="footer" class="footer">

    <div class="footer-content">
      <div class="container">

        <div class="row g-5">
          <div class="col-lg-4">
            <h3 class="footer-heading">About topDev Blog</h3>
            <p>topDev blog, is a place where we can explore the fascinating world of data and learn how to use it to make better decisions. My mission is to empower individuals and businesses to leverage data and analytics to drive innovation and growth. In today's data-driven world, data science skills are in high demand, and the ability to effectively analyze and interpret data can make all the difference between success and failure. Yet, many people are intimidated by the complexity of data science and don't know where to start. That's where topDev Blog blog in.</p>
            <p><a href="{% url "blog:about_us" %}" class="footer-link-more">Learn More</a></p>
          </div>
          <div class="col-6 col-lg-2">
            <h3 class="footer-heading">Navigation</h3>
            <ul class="footer-links list-unstyled">
              <li><a href="index.html"><i class="bi bi-chevron-right"></i> Home</a></li>
              <li><a href="index.html"><i class="bi bi-chevron-right"></i> About</a></li>
              <li><a href="category.html"><i class="bi bi-chevron-right"></i>Contact</a></li>
            </ul>
          </div>
          <div class="col-6 col-lg-2">
            <h3 class="footer-heading">Categories</h3>
            <ul class="footer-links list-unstyled">
              <li><a href="category.html"><i class="bi bi-chevron-right"></i>Machine Learnng</a></li>
              <li><a href="category.html"><i class="bi bi-chevron-right"></i>DataScience</a></li>
              <li><a href="category.html"><i class="bi bi-chevron-right"></i>Data Engineering</a></li>
              <li><a href="category.html"><i class="bi bi-chevron-right"></i>MLOps</a></li>
              <li><a href="category.html"><i class="bi bi-chevron-right"></i>Django</a></li>
              <li><a href="category.html"><i class="bi bi-chevron-right"></i>Web Scraping</a></li>
            

            </ul>
          </div>

          <div class="col-lg-4">
            <h3 class="footer-heading">Recent Posts</h3>

            <ul class="footer-links footer-blog-entry list-unstyled">
              <li>
                <a href="single-post.html" class="d-flex align-items-center">
                  <img src="assets/img/post-sq-1.jpg" alt="" class="img-fluid me-3">
                  <div>
                    <div class="post-meta d-block"><span class="date">Culture</span> <span class="mx-1">&bullet;</span> <span>Jul 5th '22</span></div>
                    <span>5 Great Startup Tips for Female Founders</span>
                  </div>
                </a>
              </li>

              <li>
                <a href="single-post.html" class="d-flex align-items-center">
                  <img src="assets/img/post-sq-2.jpg" alt="" class="img-fluid me-3">
                  <div>
                    <div class="post-meta d-block"><span class="date">Culture</span> <span class="mx-1">&bullet;</span> <span>Jul 5th '22</span></div>
                    <span>What is the son of Football Coach John Gruden, Deuce Gruden doing Now?</span>
                  </div>
                </a>
              </li>

              <li>
                <a href="single-post.html" class="d-flex align-items-center">
                  <img src="assets/img/post-sq-3.jpg" alt="" class="img-fluid me-3">
                  <div>
                    <div class="post-meta d-block"><span class="date">Culture</span> <span class="mx-1">&bullet;</span> <span>Jul 5th '22</span></div>
                    <span>Life Insurance And Pregnancy: A Working Mom’s Guide</span>
                  </div>
                </a>
              </li>

              <li>
                <a href="single-post.html" class="d-flex align-items-center">
                  <img src="assets/img/post-sq-4.jpg" alt="" class="img-fluid me-3">
                  <div>
                    <div class="post-meta d-block"><span class="date">Culture</span> <span class="mx-1">&bullet;</span> <span>Jul 5th '22</span></div>
                    <span>How to Avoid Distraction and Stay Focused During Video Calls?</span>
                  </div>
                </a>
              </li>

            </ul>

          </div>
        </div>
      </div>
    </div>

    <div class="footer-legal">
      <div class="container">

        <div class="row justify-content-between">
          <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
            <div class="copyright">
              © Copyright <strong><span>topDevs</span></strong>. All Rights Reserved
            </div>

            <div class="credits">
              
              
            </div>

          </div>

          <div class="col-md-6">
            <div class="social-links mb-3 mb-lg-0 text-center text-md-end">
              <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
              <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
              <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
              <a href="#" class="google-plus"><i class="bi bi-skype"></i></a>
              <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
            </div>

          </div>

        </div>

      </div>
    </div>

  </footer>

blog/templates/blog/base/header.html
  <!-- ======= Header ======= -->
  <header id="header" class="header d-flex align-items-center fixed-top">
    <div class="container-fluid container-xl d-flex align-items-center justify-content-between">

      <a href="index.html" class="logo d-flex align-items-center">
       
        <!-- <img src="assets/img/logo.png" alt=""> -->
        <h1>topDev</h1>
      </a>
      <nav id="navbar" class="navbar">
        <ul>
          <li><a href="{% url "blog:post_list" %}">Home</a></li>
          <li><a href="{% url "blog:about_us" %}">About</a></li>
          <li><a href="{% url "blog:post_feed" %}">Subscribe</a></li>
          <li><a href="{% url "blog:contact_us" %}">Contact</a></li>
        </ul>
      </nav><!-- .navbar -->

      <div class="position-relative">
        <a href="#" class="mx-2"><span class="bi-facebook"></span></a>
        <a href="#" class="mx-2"><span class="bi-twitter"></span></a>
        <a href="#" class="mx-2"><span class="bi-instagram"></span></a>

        <a href="#" class="mx-2 js-search-open"><span class="bi-search"></span></a>
        <i class="bi bi-list mobile-nav-toggle"></i>

        <!-- ======= Search Form ======= -->
        <div class="search-form-wrap js-search-form-wrap">
          <form action="search-result.html" class="search-form">
            <span class="icon bi-search"></span>
            <input type="text" placeholder="Search" class="form-control">
            <button class="btn js-search-close"><span class="bi-x"></span></button>
          </form>
        </div><!-- End Search Form -->

      </div>

    </div>

  </header><!-- End Header -->

blog/templates/blog/base/scripts.html
{% load static %}



 <!-- Vendor CSS Files -->
 <link href="{%static "assets/vendor/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">
 <link href="{%static "assets/vendor/bootstrap-icons/bootstrap-icons.css" %}" rel="stylesheet">
 <link href="{%static "assets/vendor/swiper/swiper-bundle.min.css" %}" rel="stylesheet">
 <link href="{%static "assets/vendor/glightbox/css/glightbox.min.css" %}" rel="stylesheet">
 <link href="{%static "assets/vendor/aos/aos.css" %}"rel="stylesheet">

 <!-- Template Main CSS Files -->
 <link href="{%static "assets/css/variables.css" %}" rel="stylesheet">
 <link href="{%static "assets/css/main.css" %}" rel="stylesheet">
 <link href="{%static "assets/css/styles.css" %}" rel="stylesheet">
  <!-- Vendor JS Files -->
  <script src="{%static "assets/vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
  <script src="{%static "assets/vendor/swiper/swiper-bundle.min.js" %}"></script>
  <script src="{%static "assets/vendor/glightbox/js/glightbox.min.js" %}"></script>
  <script src="{%static "assets/vendor/aos/aos.js" %}"></script>
  <script src="{%static "assets/vendor/php-email-form/validate.js" %}"></script>

  <!-- Template Main JS File -->
  <script src="{%static "assets/js/main.js" %}"></script>