blog/urls.py
from django.urls import path
from . import views
from django.contrib.sitemaps.views import sitemap
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
 # post views
 path('', views.post_list, name='post_list'),
 path('tag/<slug:tag_slug>/',
      views.post_list, 
      name='post_list_by_tag'),
 path('<int:year>/<int:month>/<int:day>/<slug:post>/',
      views.post_detail,
      name='post_detail'),
path('<int:post_id>/share/',
      views.post_share, 
      name='post_share'),
path('<int:post_id>/comment/',
      views.post_comment, name='post_comment'),
path('feed/', LatestPostsFeed(), name='post_feed'),
path('about/', views.about_us, name='about_us'),
path('contactus/', views.contact_us, name='contact_us'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap



sitemaps = {
 'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('ckeditor/',include('ckeditor_uploader.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap')
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
from ckeditor_uploader.fields import RichTextUploadingField 

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)
    
class Post(models.Model):
    
    class Status(models.TextChoices):
          DRAFT = 'DF', 'Draft'
          PUBLISHED = 'PB', 'Published'
                     
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    author = models.ForeignKey(User,
                on_delete=models.CASCADE,
                related_name='blog_posts')
    body=RichTextUploadingField() 
    body_summary=models.TextField(max_length=500)
    image = models.ImageField(upload_to='media/Post_images/%Y/%m/%d/')
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2,
                                choices=Status.choices,
                                default=Status.DRAFT)
    objects = models.Manager() # The default manager.
    published = PublishedManager() # Our custom manager.
    tags = TaggableManager()
    
    class Meta:
          ordering = ['-publish']
          verbose_name_plural = "Post" 
          indexes = [
             models.Index(fields=['-publish']),
            ]
 
 
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('blog:post_detail',
                        args=[
                             self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug])
                  
class Email(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    to = models.EmailField()
    comments = models.CharField(max_length=50)

    def __str__(self):
        return self.name  
    
    class Meta:
        verbose_name_plural = "Email"  
    
    
    
class Comment(models.Model):
    post = models.ForeignKey(Post,
                                on_delete=models.CASCADE,
                                related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    
    class Meta:
        ordering = ['created']
        verbose_name_plural = "Comment" 
        indexes = [
                 models.Index(fields=['created']),
        ]
        
    def __str__(self):
        return f'Comment by {self.name} on {self.post}'  

class Contact(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    subject = models.CharField(max_length=50)
    message = models.TextField(max_length=100)

    def __str__(self):
        return self.name
    class Meta:
        verbose_name_plural = "Contact"  

class About(models.Model):
    mission = models.TextField(max_length=1000)
    aboutme = models.TextField(max_length=1000)
    mission_pic = models.ImageField(upload_to='media/Mission_images/%Y/%m/%d/')
    aboutme_pic = models.ImageField(upload_to='media/Aboutme_images/%Y/%m/%d/')
    
    class Meta:
        verbose_name_plural = "About"
  
    
    
class OurTeam(models.Model):
    name = models.CharField(max_length=50)
    position = models.CharField(max_length=50)
    profile = models.ImageField(upload_to='media/Ourteam_images/%Y/%m/%d/')
    about= models.TextField(max_length=1000)

    def __str__(self):
        return self.name 
    
    class Meta:
        verbose_name_plural = "OurTeam"

    
    
class Contact_details(models.Model):
    Address = models.CharField(max_length=100)
    phone_Number = models.CharField(max_length=50)
    email = models.EmailField()
    
    def __str__(self):
        return self.email
    
    class Meta:
        verbose_name_plural = "Contact_details"

                       
                        
                         

blog/forms.py
from django import forms
from .models import Email,Comment,Contact

class EmailPostForm(forms.ModelForm):
    class Meta:
        model = Email
        fields = '__all__'
        widgets = {
            'name':forms.TextInput(attrs={'class':'form-control'}),   
            'email':forms.EmailInput(attrs={'class':'form-control'}), 
            'to':forms.TextInput(attrs={'class':'form-control'}), 
            'comments':forms.Textarea(attrs={'class':'form-control'}), 
        }
        
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']
        widgets = {
            'name':forms.TextInput(attrs={'class':'form-control'}),   
            'email':forms.EmailInput(attrs={'class':'form-control'}), 
            'body':forms.Textarea(attrs={'class':'form-control'}), 
        }

class SearchForm(forms.Form):
      query = forms.CharField()
          
class Contactform(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'
        widgets = {
            'name':forms.TextInput(attrs={'class':'form-control'}),   
            'email':forms.EmailInput(attrs={'class':'form-control'}), 
            'subject':forms.TextInput(attrs={'class':'form-control'}), 
            'Message':forms.Textarea(attrs={'class':'form-control'}), 
        }

blog/views.py
from django.shortcuts import render
from .models import Post,Comment,About,OurTeam,Contact_details
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.core.mail import send_mail
from .forms import EmailPostForm, CommentForm,SearchForm,Contactform
from django.views.decorators.http import require_POST
from taggit.models import Tag
from django.db.models import Count
from django.contrib.postgres.search import SearchVector

def post_list(request, tag_slug=None):
    post_list = Post.published.all()
    tag = None
    if tag_slug:
       tag = get_object_or_404(Tag, slug=tag_slug)
       post_list = post_list.filter(tags__in=[tag])

    # Pagination with 3 posts per page
    paginator = Paginator(post_list, 3)
    page_number = request.GET.get('page', 1)
    try:
            posts = paginator.page(page_number)
            
    except PageNotAnInteger:
           # If page_number is not an integer deliver the first page
           posts = paginator.page(1)
    except EmptyPage:
            # If page_number is out of range deliver last page of results
            posts = paginator.page(paginator.num_pages)
    return render(request,
                 'blog/post/list.html',
                 {'posts': posts,
                  'tag': tag})
    
    
def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post,
                             status=Post.Status.PUBLISHED,
                             slug=post,
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)
    # List of active comments for this post
    comments = post.comments.filter(active=True)
    # Form for users to comment
    form = CommentForm()
    # List of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:4]
    return render(request,
                'blog/post/detail.html',
                {'post': post,
                'comments': comments,
                'form': form,
                'similar_posts': similar_posts})

def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    sent = False
    
    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(
                                                  post.get_absolute_url())
            subject = f"{cd['name']} recommends you read " f"{post.title}"
            message = f"Read {post.title} at {post_url}\n\n" f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'junioralexio607@gmail.com',
            [cd['to']])
            sent = True
            # ... send email
            # Save the email to the database
            form.save()
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post,
                            'form': form,
                            'sent': sent})
    
@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None
    # A comment was posted
    form = CommentForm(data=request.POST)
    if form.is_valid():
        # Create a Comment object without saving it to the database
        comment = form.save(commit=False)
        # Assign the post to the comment
        comment.post = post
        # Save the comment to the database
        comment.save()
    return render(request, 'blog/post/comment.html',
                            {'post': post,
                            'form': form,
                            'comment': comment})  
    
def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = Post.published.annotate(search=SearchVector('title', 'body'),).filter(search=query)
            return render(request,
                         'blog/post/search.html',
                         {'form': form,
                         'query': query,
                         'results': results})
 
def contact_us(request):
    Contact_info = Contact_details.objects.all()
    if request.method == 'POST':
        # Form was submitted
        form = Contactform(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            subject = f"{cd['name']}  with email {cd['email']}  Sent you a message  from  topDevBlog:{cd['subject']} "
            message = f"Message: {cd['message']}"
            send_mail(subject, message, 'junioralexio607@gmail.com',
            ['junioralexio607@gmail.com'])
            sent = True
            # ... send email
            return render(request, 'blog/post/contact.html', 
                  {'Contact_info': Contact_info,
                   'form': form,
                   'sent': sent})
        
    else:
        form = Contactform()
    return render(request, 'blog/post/contact.html', 
                  {'Contact_info': Contact_info,
                   'form': form})

def about_us(request):
    about = About.objects.all()
    ourteam = OurTeam.objects.all()
    
    return render(request,
                'blog/post/about.html',
                {'about': about,
                'ourteam': ourteam,
                })
    

blog/templates/blog/post/about.html
{% extends "blog/base/base.html" %}

{% block title %}About Us{% endblock %}


{% block content %}



<main id="main">
  <section>
    <div class="container" data-aos="fade-up">
      <div class="row">
        <div class="col-lg-12 text-center mb-5">
          <h1 class="page-title">About us</h1>
        </div>
      </div>
      {% for post in about %}
      <div class="row mb-5">

       

        <div class="d-md-flex post-entry-2 half">
          <a href="#" class="me-4 thumbnail">
            <img src="{{post.aboutme_pic.url}}" alt="" class="img-fluid">
          </a>
          <div class="ps-md-5 mt-4 mt-md-0">
            <div class="post-meta mt-4">About us</div>
            <h2 class="mb-4 display-4">About Me</h2>

            <p> {{post.aboutme}}  </p>
          </div>
        </div>


  
        <div class="d-md-flex post-entry-2 half mt-5">
          <a href="#" class="me-4 thumbnail order-2">
            <img src="{{post.mission_pic.url}}" alt="" class="img-fluid">
          </a>
          <div class="pe-md-5 mt-4 mt-md-0">
            <div class="post-meta mt-4">Mission &amp; Vision</div>
            <h2 class="mb-4 display-4">Mission &amp; Vision</h2>

            <p>{{post.mission}}</p>
            
          </div>
        </div>


        {% endfor %}


      </div>

    </div>
  </section>



</main><!-- End #main -->

<a href="#" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>


{% endblock %}

blog/templates/blog/post/comment.html
{% extends "blog/base/base.html" %}


{% block title %}Add a comment{% endblock %}


{% block content %}


<main id="main">
 {% if comment %}
 <h2>Your comment has been added.</h2>
 <p><a href="{{ post.get_absolute_url }}">Back to the post</a></p>
 {% else %}
 {% include "blog/post/includes/comment_form.html" %}
 {% endif %}
</main><!-- End #main -->
{% endblock %}

blog/templates/blog/post/contact.html
{% extends "blog/base/base.html" %}



{% block title %}topDev Blog{% endblock %}




{% block content %}




<main id="main">
  <section id="contact" class="contact mb-5">
    <div class="container" data-aos="fade-up">

      <div class="row">
        <div class="col-lg-12 text-center mb-5">
          <h1 class="page-title">Contact us</h1>
        </div>
      </div>

      <div class="row gy-4">
{%   for detail in Contact_info%}
        <div class="col-md-4">
          <div class="info-item">
            <i class="bi bi-geo-alt"></i>
            <h3>Address</h3>
            <address>{{detail.Address}}</address>
          </div>
        </div><!-- End Info Item -->

        

       

        <div class="col-md-4">
          <div class="info-item info-item-borders">
            <i class="bi bi-phone"></i>
            <h3>Phone Number</h3>
            <p><a href="tel:+155895548855">{{detail.phone_Number}}</a></p>
          </div>
        </div><!-- End Info Item -->

        <div class="col-md-4">
          <div class="info-item">
            <i class="bi bi-envelope"></i>
            <h3>Email</h3>
            <p><a href="mailto:junioralexio607@gmail.com">{{detail.email}}</a></p>
          </div>
        </div><!-- End Info Item -->

      </div>


      {% endfor%}

     
      <style>
        .Contactus_form{
          border: 2px ;
         
          padding-top: 80px;
          padding-right: 30px;
          padding-bottom: 50px;
          padding-left: 80px;
        }
        </style>

       
      <div   class="Contactus_form">  
      {% if sent %}
      <h3>Thank you for contacting us, we will get back to you as soon as possible.</h3>
      <p>
      
      </p>
      {% else %}

      <div class="form mt-5">
        <form action="#" method="post" role="form" class="php-email-form">
          <div class="row">
            <div class="form-group col-md-6">
              {% csrf_token %}
              {{ form.as_p }}
            </div>

          <div class="text-center"><button type="submit">Send Message</button></div>
        </form>
      </div><!-- End Contact Form -->
      {% endif %}


    
  </div>

    </div>
  </section>

</main><!-- End #main -->



<a href="#" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>


{% endblock %}

blog/templates/blog/post/detail.html
{% extends "blog/base/base.html" %}
{% load blog_tags %}


{% block title %} {{ post.title }} {% endblock %}



{% block content %}


<main id="main">

  <section class="single-post-content">
    <div class="container">
      <div class="row">
        <div class="col-md-9 post-content" data-aos="fade-up">

          <!-- ======= Single Post Content ======= -->
          <div class="single-post">
            <div class="post-meta"><span class="date"></span> <span class="mx-1">&bullet;</span> <span>{{ post.publish }}</span></div>
            <h1 class="mb-5">{{ post.title }}</h1>

            <p>{{ post.body|safe }}</p>
            <p>
              <a href="{% url "blog:post_share" post.id %}" class="btn btn-primary" role="button" >Share this post</a>
            </p>
          </div><!-- End Single Post Content -->

        </div>
        <div class="col-md-3">
          <!-- ======= Sidebar ======= -->
          <div class="aside-block">

            <ul class="nav nav-pills custom-tab-nav mb-4" id="pills-tab" role="tablist">
              <li class="nav-item" role="presentation">
                <button class="nav-link active" id="pills-popular-tab" data-bs-toggle="pill" data-bs-target="#pills-popular" type="button" role="tab" aria-controls="pills-popular" aria-selected="true">similar Posts</button>
              </li>

              </li>
            </ul>

            <div class="tab-content" id="pills-tabContent">
              {% for post in similar_posts %}
              <!-- Popular -->
              <div class="tab-pane fade show active" id="pills-popular" role="tabpanel" aria-labelledby="pills-popular-tab">
                <div class="post-entry-1 border-bottom">
                  <div class="post-meta"><span class="date">Sport</span> <span class="mx-1">&bullet;</span> <span>{{ post.created }}</span></div>
                  <h2 class="mb-2"><a href="{{ post.get_absolute_url }}">{{ post.title }}</h2>
                  <span class="author mb-3 d-block">{{ post.author }}</span>
                </div>
                {% empty %}
                There are no similar posts yet.
            {% endfor %}
              </div> <!-- End Popular -->

           

       
            </div>
          </div>


          <div class="aside-block">
            <h3 class="aside-title">Tags</h3>
            <ul class="aside-tags list-unstyled">
              <li><a href="#">{{ post.tags.all|join:", " }}</a></li>
            </ul>
          </div><!-- End Tags -->
        </div>
      </div>

      
    </div>

    
  </section>


  
  
  {% for comment in comments %}
  <!-- ======= Comments ======= -->

  <div class="comments">

    <h5 class="comment-title py-4">Comment {{ forloop.counter }} </h5>
 

    <div class="comment d-flex">
      <div class="flex-shrink-0">
        <div class="avatar avatar-sm rounded-circle">
          <img class="avatar-img" src="assets/img/person-2.jpg" alt="" class="img-fluid">
        </div>
      </div>
      <div class="flex-shrink-1 ms-2 ms-sm-3">
        <div class="comment-meta d-flex">
          <h6 class="me-2">{{ comment.name }}</h6>
          <span class="text-muted">{{ comment.created }}</span>
        </div>
        <div class="comment-body">
          {{ comment.body|linebreaks }}
        </div>
      </div>
    </div>
  </div><!-- End Comments -->
  {% empty %}
            <p>There are no comments.</p>
          </div>
  {% endfor %}
  
  {% include "blog/post/includes/comment_form.html" %}
  
</main><!-- End #main -->


<a href="#" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>





{% endblock %}



























  
  

blog/templates/blog/post/list.html
{% extends "blog/base/base.html" %}
{% load blog_tags %}





{% block title %}topDev Blog{% endblock %}




{% block content %}
 


<body>
    <main id="main">
  
       <!-- ======= Hero Slider Section ======= -->
      <section id="hero-slider" class="hero-slider">
        <div class="container-md" data-aos="fade-in">
          <div class="row">
            <div class="col-12">
              <div class="swiper sliderFeaturedPosts">
                <div class="swiper-wrapper">
                  {% for post in posts %}
                  <div class="swiper-slide">
                    <a href="{{ post.get_absolute_url }}" class="img-bg d-flex align-items-end" style="background-image: url({{ post.image.url }});">
                      <div class="img-bg-inner">
                        <h2>{{post.title}}</h2>
                         <p>{{ post.body_summary|truncatewords_html:30}}</p>
                      </div>
                    </a>
                  </div>

                  {% endfor %}

                </div>
                <div class="custom-swiper-button-next">
                  <span class="bi-chevron-right"></span>
                </div>
                <div class="custom-swiper-button-prev">
                  <span class="bi-chevron-left"></span>
                </div>
  
                <div class="swiper-pagination"></div>
              </div>
            </div>
          </div>
        </div>
      </section><!-- End Hero Slider Section -->
  
      <!-- ======= Culture Category Section ======= -->
      <section class="category-section">
        <div class="container" data-aos="fade-up">
  
          <div class="section-header d-flex justify-content-between align-items-center mb-5">
            <h2>Blogs</h2>
            <div><a href="{% url "blog:post_feed" %}" class="more">Subscribe To our Feeds</a></div>
          </div>
  
          <div class="row">
            <div class="col-md-9">


              {% for post in posts %}
  
              <div class="d-lg-flex post-entry-2">
                <a href="{{ post.get_absolute_url }}" class="me-4 thumbnail mb-4 mb-lg-0 d-inline-block">
                  <img src="{{post.image.url}}" alt="IMG....." class="img-fluid">
                </a>
                <div>
                  <div class="post-meta"><span class="date">Culture</span> <span class="mx-1">&bullet;</span> <span>{{ post.publish }}</span></div>
                  <h3><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>  
                  <p>{{ post.body|safe|truncatewords_html:30  }}</p>
                  <div class="d-flex align-items-center author">
                    <div class="photo"><img src="{{post.image.url}}" alt="IMG....." class="img-fluid"></div>
                    <div class="name">
                      <h3 class="m-0 p-0">{{ post.author }}</h3>
                    </div>
                  </div>
                </div>
              </div>
                
              {% endfor %}

            </div>
          </div>
  
              <!-- Trending Section -->
              <div class="col-lg-4">
  
                <div class="trending">
                  <h3 id="heading">Most Trending</h3>
                  <ul class="trending-post">

                    {% get_most_commented_posts as most_commented_posts %}
                    {% for post in most_commented_posts %}
                    <li>
                      <a href="{{ post.get_absolute_url }}">
                        <span class="number"></span>
                        
                        <h3>{{ post.title }}</h3>
                        <span class="author">{{ post.author}}</span>
                      </a>
                    </li>
                    {% endfor %}

                  </ul>
                </div>

              </div> <!-- End Trending Section -->




           





      </section><!-- End Culture Category Section -->
  
     
  {% include "blog/post/pagination.html" with page=posts %}

  
    </main><!-- End #main -->
  
  
    <a href="#" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>
  
  
  
  </body>

{% endblock %}

blog/templates/blog/post/pagination.html
        <!-- Paging -->
        <div class="text-start py-4">
            <div class="custom-pagination">
                {% if page.has_previous %}
              <a href="?page={{ page.previous_page_number }}" class="prev">Prevous</a>
              {% endif %}
              <a href="#" class="active">{{ page.number }}</a> of
              <a href="#">{{ page.paginator.num_pages }}</a>
              {% if page.has_next %}
              <a href="?page={{ page.next_page_number }}" class="next">Next</a>
              {% endif %}
            </div>
          </div><!-- End Paging -->

blog/templates/blog/post/scratch.html
{% extends "blog/base/base.html" %}



{% block title %}topDev Blog{% endblock %}




{% block content %}

{% endblock %}







<div class="loading">Loading</div>
<div class="error-message"></div>
<div class="sent-message">Your message has been sent. Thank you!</div>
</div>

blog/templates/blog/post/share.html
{% extends "blog/base/base.html" %}



{% block title %}Share a post{% endblock %}




{% block content %}

<main id="main">
 {% if sent %}
 <h1>E-mail successfully sent</h1>
 <p>
 "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
 </p>
 {% else %}
 <h1>Share "{{ post.title }}" by e-mail</h1>

 <!-- ======= Comments Form ======= -->
 <div class="row justify-content-center mt-5">
<form     method="POST">
  <div class="col-lg-12">
    <h5 class="comment-title">Share with a friend</h5>
    <div class="row">
      <div class="col-lg-6 mb-3">
        {% csrf_token %}
        {{ form.as_p }}
       
        <div class="col-12">
          <input type="submit" class="btn btn-primary" value="Post comment">
        </div>
      </div>
    </div>
 
</form>
{% endif %}
</div><!-- End Comments Form -->

</main><!-- End #main -->

{% endblock %}